// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD243UD4dDDRISNaithMGeMQRSUGOhIas4',
    appId: '1:485339877723:web:c9d19c2b3dd0067835ca7e',
    messagingSenderId: '485339877723',
    projectId: 'fooddeliveryapp-1fe78',
    authDomain: 'fooddeliveryapp-1fe78.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-1fe78.appspot.com',
    measurementId: 'G-0W8CRVB1BR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR7ylnBW5zgg3d9a-BkwOVSlQiBf8ZIoM',
    appId: '1:485339877723:android:4f3cfc6359d1bce035ca7e',
    messagingSenderId: '485339877723',
    projectId: 'fooddeliveryapp-1fe78',
    storageBucket: 'fooddeliveryapp-1fe78.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBngkVGO6O7N9smgwNcmgh2pbBuVs8WA0E',
    appId: '1:485339877723:ios:c2f3a0c68acfa68935ca7e',
    messagingSenderId: '485339877723',
    projectId: 'fooddeliveryapp-1fe78',
    storageBucket: 'fooddeliveryapp-1fe78.appspot.com',
    iosBundleId: 'com.example.myFood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBngkVGO6O7N9smgwNcmgh2pbBuVs8WA0E',
    appId: '1:485339877723:ios:93f5cd31fdf74ccb35ca7e',
    messagingSenderId: '485339877723',
    projectId: 'fooddeliveryapp-1fe78',
    storageBucket: 'fooddeliveryapp-1fe78.appspot.com',
    iosBundleId: 'com.example.myFood.RunnerTests',
  );
}
